-- ==============================================================
-- PMS Project: Countries Table with Dial Codes & Digit Rules
-- Ready to import directly into MySQL / phpMyAdmin
-- ==============================================================

-- 1. Ensure table structure exists
CREATE TABLE IF NOT EXISTS `countries` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(191) NOT NULL,
  `phone_code` VARCHAR(10) NULL,
  `iso_code` VARCHAR(10) NULL,
  `min_digits` INT DEFAULT 10,
  `max_digits` INT DEFAULT 10,
  `flag_url` VARCHAR(255) NULL,
  UNIQUE KEY `countries_name_unique` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Ensure columns exist if table was previously created with only (id, name)
SET @dbname = DATABASE();
SET @tablename = 'countries';

SET @sql_phone = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME = @tablename AND COLUMN_NAME = 'phone_code') > 0, 'SELECT 1', 'ALTER TABLE `countries` ADD COLUMN `phone_code` VARCHAR(10) NULL AFTER `name`'));
PREPARE stmt_phone FROM @sql_phone; EXECUTE stmt_phone; DEALLOCATE PREPARE stmt_phone;

SET @sql_iso = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME = @tablename AND COLUMN_NAME = 'iso_code') > 0, 'SELECT 1', 'ALTER TABLE `countries` ADD COLUMN `iso_code` VARCHAR(10) NULL AFTER `phone_code`'));
PREPARE stmt_iso FROM @sql_iso; EXECUTE stmt_iso; DEALLOCATE PREPARE stmt_iso;

SET @sql_min = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME = @tablename AND COLUMN_NAME = 'min_digits') > 0, 'SELECT 1', 'ALTER TABLE `countries` ADD COLUMN `min_digits` INT DEFAULT 10 AFTER `iso_code`'));
PREPARE stmt_min FROM @sql_min; EXECUTE stmt_min; DEALLOCATE PREPARE stmt_min;

SET @sql_max = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME = @tablename AND COLUMN_NAME = 'max_digits') > 0, 'SELECT 1', 'ALTER TABLE `countries` ADD COLUMN `max_digits` INT DEFAULT 10 AFTER `min_digits`'));
PREPARE stmt_max FROM @sql_max; EXECUTE stmt_max; DEALLOCATE PREPARE stmt_max;

SET @sql_flag = (SELECT IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME = @tablename AND COLUMN_NAME = 'flag_url') > 0, 'SELECT 1', 'ALTER TABLE `countries` ADD COLUMN `flag_url` VARCHAR(255) NULL AFTER `max_digits`'));
PREPARE stmt_flag FROM @sql_flag; EXECUTE stmt_flag; DEALLOCATE PREPARE stmt_flag;

-- 3. Insert or update 194 countries with dial codes, ISO codes, digit rules, and flags
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('India', '+91', 'IN', 10, 10, 'https://flagcdn.com/w20/in.png') ON DUPLICATE KEY UPDATE `phone_code` = '+91', `iso_code` = 'IN', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/in.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Afghanistan', '+93', 'AF', 9, 9, 'https://flagcdn.com/w20/af.png') ON DUPLICATE KEY UPDATE `phone_code` = '+93', `iso_code` = 'AF', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/af.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Albania', '+355', 'AL', 9, 9, 'https://flagcdn.com/w20/al.png') ON DUPLICATE KEY UPDATE `phone_code` = '+355', `iso_code` = 'AL', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/al.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Algeria', '+213', 'DZ', 9, 9, 'https://flagcdn.com/w20/dz.png') ON DUPLICATE KEY UPDATE `phone_code` = '+213', `iso_code` = 'DZ', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/dz.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Andorra', '+376', 'AD', 6, 9, 'https://flagcdn.com/w20/ad.png') ON DUPLICATE KEY UPDATE `phone_code` = '+376', `iso_code` = 'AD', `min_digits` = 6, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/ad.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Angola', '+244', 'AO', 9, 9, 'https://flagcdn.com/w20/ao.png') ON DUPLICATE KEY UPDATE `phone_code` = '+244', `iso_code` = 'AO', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/ao.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Argentina', '+54', 'AR', 10, 10, 'https://flagcdn.com/w20/ar.png') ON DUPLICATE KEY UPDATE `phone_code` = '+54', `iso_code` = 'AR', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/ar.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Armenia', '+374', 'AM', 8, 8, 'https://flagcdn.com/w20/am.png') ON DUPLICATE KEY UPDATE `phone_code` = '+374', `iso_code` = 'AM', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/am.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Australia', '+61', 'AU', 9, 9, 'https://flagcdn.com/w20/au.png') ON DUPLICATE KEY UPDATE `phone_code` = '+61', `iso_code` = 'AU', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/au.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Austria', '+43', 'AT', 10, 11, 'https://flagcdn.com/w20/at.png') ON DUPLICATE KEY UPDATE `phone_code` = '+43', `iso_code` = 'AT', `min_digits` = 10, `max_digits` = 11, `flag_url` = 'https://flagcdn.com/w20/at.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Azerbaijan', '+994', 'AZ', 9, 9, 'https://flagcdn.com/w20/az.png') ON DUPLICATE KEY UPDATE `phone_code` = '+994', `iso_code` = 'AZ', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/az.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Bahamas', '+1', 'BS', 10, 10, 'https://flagcdn.com/w20/bs.png') ON DUPLICATE KEY UPDATE `phone_code` = '+1', `iso_code` = 'BS', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/bs.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Bahrain', '+973', 'BH', 8, 8, 'https://flagcdn.com/w20/bh.png') ON DUPLICATE KEY UPDATE `phone_code` = '+973', `iso_code` = 'BH', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/bh.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Bangladesh', '+880', 'BD', 10, 10, 'https://flagcdn.com/w20/bd.png') ON DUPLICATE KEY UPDATE `phone_code` = '+880', `iso_code` = 'BD', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/bd.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Barbados', '+1', 'BB', 10, 10, 'https://flagcdn.com/w20/bb.png') ON DUPLICATE KEY UPDATE `phone_code` = '+1', `iso_code` = 'BB', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/bb.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Belarus', '+375', 'BY', 9, 9, 'https://flagcdn.com/w20/by.png') ON DUPLICATE KEY UPDATE `phone_code` = '+375', `iso_code` = 'BY', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/by.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Belgium', '+32', 'BE', 9, 9, 'https://flagcdn.com/w20/be.png') ON DUPLICATE KEY UPDATE `phone_code` = '+32', `iso_code` = 'BE', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/be.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Belize', '+501', 'BZ', 7, 7, 'https://flagcdn.com/w20/bz.png') ON DUPLICATE KEY UPDATE `phone_code` = '+501', `iso_code` = 'BZ', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/bz.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Benin', '+229', 'BJ', 8, 8, 'https://flagcdn.com/w20/bj.png') ON DUPLICATE KEY UPDATE `phone_code` = '+229', `iso_code` = 'BJ', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/bj.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Bhutan', '+975', 'BT', 8, 8, 'https://flagcdn.com/w20/bt.png') ON DUPLICATE KEY UPDATE `phone_code` = '+975', `iso_code` = 'BT', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/bt.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Bolivia', '+591', 'BO', 8, 8, 'https://flagcdn.com/w20/bo.png') ON DUPLICATE KEY UPDATE `phone_code` = '+591', `iso_code` = 'BO', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/bo.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Bosnia and Herzegovina', '+387', 'BA', 8, 8, 'https://flagcdn.com/w20/ba.png') ON DUPLICATE KEY UPDATE `phone_code` = '+387', `iso_code` = 'BA', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/ba.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Botswana', '+267', 'BW', 8, 8, 'https://flagcdn.com/w20/bw.png') ON DUPLICATE KEY UPDATE `phone_code` = '+267', `iso_code` = 'BW', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/bw.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Brazil', '+55', 'BR', 10, 11, 'https://flagcdn.com/w20/br.png') ON DUPLICATE KEY UPDATE `phone_code` = '+55', `iso_code` = 'BR', `min_digits` = 10, `max_digits` = 11, `flag_url` = 'https://flagcdn.com/w20/br.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Brunei', '+673', 'BN', 7, 7, 'https://flagcdn.com/w20/bn.png') ON DUPLICATE KEY UPDATE `phone_code` = '+673', `iso_code` = 'BN', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/bn.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Bulgaria', '+359', 'BG', 9, 9, 'https://flagcdn.com/w20/bg.png') ON DUPLICATE KEY UPDATE `phone_code` = '+359', `iso_code` = 'BG', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/bg.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Burkina Faso', '+226', 'BF', 8, 8, 'https://flagcdn.com/w20/bf.png') ON DUPLICATE KEY UPDATE `phone_code` = '+226', `iso_code` = 'BF', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/bf.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Burundi', '+257', 'BI', 8, 8, 'https://flagcdn.com/w20/bi.png') ON DUPLICATE KEY UPDATE `phone_code` = '+257', `iso_code` = 'BI', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/bi.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Cambodia', '+855', 'KH', 8, 9, 'https://flagcdn.com/w20/kh.png') ON DUPLICATE KEY UPDATE `phone_code` = '+855', `iso_code` = 'KH', `min_digits` = 8, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/kh.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Cameroon', '+237', 'CM', 9, 9, 'https://flagcdn.com/w20/cm.png') ON DUPLICATE KEY UPDATE `phone_code` = '+237', `iso_code` = 'CM', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/cm.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Canada', '+1', 'CA', 10, 10, 'https://flagcdn.com/w20/ca.png') ON DUPLICATE KEY UPDATE `phone_code` = '+1', `iso_code` = 'CA', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/ca.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Cape Verde', '+238', 'CV', 7, 7, 'https://flagcdn.com/w20/cv.png') ON DUPLICATE KEY UPDATE `phone_code` = '+238', `iso_code` = 'CV', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/cv.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Central African Republic', '+236', 'CF', 8, 8, 'https://flagcdn.com/w20/cf.png') ON DUPLICATE KEY UPDATE `phone_code` = '+236', `iso_code` = 'CF', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/cf.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Chad', '+235', 'TD', 8, 8, 'https://flagcdn.com/w20/td.png') ON DUPLICATE KEY UPDATE `phone_code` = '+235', `iso_code` = 'TD', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/td.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Chile', '+56', 'CL', 9, 9, 'https://flagcdn.com/w20/cl.png') ON DUPLICATE KEY UPDATE `phone_code` = '+56', `iso_code` = 'CL', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/cl.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('China', '+86', 'CN', 11, 11, 'https://flagcdn.com/w20/cn.png') ON DUPLICATE KEY UPDATE `phone_code` = '+86', `iso_code` = 'CN', `min_digits` = 11, `max_digits` = 11, `flag_url` = 'https://flagcdn.com/w20/cn.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Colombia', '+57', 'CO', 10, 10, 'https://flagcdn.com/w20/co.png') ON DUPLICATE KEY UPDATE `phone_code` = '+57', `iso_code` = 'CO', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/co.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Comoros', '+269', 'KM', 7, 7, 'https://flagcdn.com/w20/km.png') ON DUPLICATE KEY UPDATE `phone_code` = '+269', `iso_code` = 'KM', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/km.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Congo', '+242', 'CG', 9, 9, 'https://flagcdn.com/w20/cg.png') ON DUPLICATE KEY UPDATE `phone_code` = '+242', `iso_code` = 'CG', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/cg.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Congo (Brazzaville)', '+242', 'CG', 9, 9, 'https://flagcdn.com/w20/cg.png') ON DUPLICATE KEY UPDATE `phone_code` = '+242', `iso_code` = 'CG', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/cg.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Congo (Kinshasa)', '+243', 'CD', 9, 9, 'https://flagcdn.com/w20/cd.png') ON DUPLICATE KEY UPDATE `phone_code` = '+243', `iso_code` = 'CD', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/cd.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Costa Rica', '+506', 'CR', 8, 8, 'https://flagcdn.com/w20/cr.png') ON DUPLICATE KEY UPDATE `phone_code` = '+506', `iso_code` = 'CR', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/cr.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Croatia', '+385', 'HR', 8, 9, 'https://flagcdn.com/w20/hr.png') ON DUPLICATE KEY UPDATE `phone_code` = '+385', `iso_code` = 'HR', `min_digits` = 8, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/hr.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Cuba', '+53', 'CU', 8, 8, 'https://flagcdn.com/w20/cu.png') ON DUPLICATE KEY UPDATE `phone_code` = '+53', `iso_code` = 'CU', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/cu.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Cyprus', '+357', 'CY', 8, 8, 'https://flagcdn.com/w20/cy.png') ON DUPLICATE KEY UPDATE `phone_code` = '+357', `iso_code` = 'CY', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/cy.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Czech Republic', '+420', 'CZ', 9, 9, 'https://flagcdn.com/w20/cz.png') ON DUPLICATE KEY UPDATE `phone_code` = '+420', `iso_code` = 'CZ', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/cz.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Denmark', '+45', 'DK', 8, 8, 'https://flagcdn.com/w20/dk.png') ON DUPLICATE KEY UPDATE `phone_code` = '+45', `iso_code` = 'DK', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/dk.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Djibouti', '+253', 'DJ', 8, 8, 'https://flagcdn.com/w20/dj.png') ON DUPLICATE KEY UPDATE `phone_code` = '+253', `iso_code` = 'DJ', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/dj.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Dominica', '+1', 'DM', 10, 10, 'https://flagcdn.com/w20/dm.png') ON DUPLICATE KEY UPDATE `phone_code` = '+1', `iso_code` = 'DM', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/dm.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Dominican Republic', '+1', 'DO', 10, 10, 'https://flagcdn.com/w20/do.png') ON DUPLICATE KEY UPDATE `phone_code` = '+1', `iso_code` = 'DO', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/do.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Ecuador', '+593', 'EC', 9, 9, 'https://flagcdn.com/w20/ec.png') ON DUPLICATE KEY UPDATE `phone_code` = '+593', `iso_code` = 'EC', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/ec.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Egypt', '+20', 'EG', 10, 10, 'https://flagcdn.com/w20/eg.png') ON DUPLICATE KEY UPDATE `phone_code` = '+20', `iso_code` = 'EG', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/eg.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('El Salvador', '+503', 'SV', 8, 8, 'https://flagcdn.com/w20/sv.png') ON DUPLICATE KEY UPDATE `phone_code` = '+503', `iso_code` = 'SV', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/sv.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Equatorial Guinea', '+240', 'GQ', 9, 9, 'https://flagcdn.com/w20/gq.png') ON DUPLICATE KEY UPDATE `phone_code` = '+240', `iso_code` = 'GQ', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/gq.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Eritrea', '+291', 'ER', 7, 7, 'https://flagcdn.com/w20/er.png') ON DUPLICATE KEY UPDATE `phone_code` = '+291', `iso_code` = 'ER', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/er.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Estonia', '+372', 'EE', 7, 8, 'https://flagcdn.com/w20/ee.png') ON DUPLICATE KEY UPDATE `phone_code` = '+372', `iso_code` = 'EE', `min_digits` = 7, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/ee.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Eswatini', '+268', 'SZ', 8, 8, 'https://flagcdn.com/w20/sz.png') ON DUPLICATE KEY UPDATE `phone_code` = '+268', `iso_code` = 'SZ', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/sz.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Ethiopia', '+251', 'ET', 9, 9, 'https://flagcdn.com/w20/et.png') ON DUPLICATE KEY UPDATE `phone_code` = '+251', `iso_code` = 'ET', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/et.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Fiji', '+679', 'FJ', 7, 7, 'https://flagcdn.com/w20/fj.png') ON DUPLICATE KEY UPDATE `phone_code` = '+679', `iso_code` = 'FJ', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/fj.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Finland', '+358', 'FI', 9, 10, 'https://flagcdn.com/w20/fi.png') ON DUPLICATE KEY UPDATE `phone_code` = '+358', `iso_code` = 'FI', `min_digits` = 9, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/fi.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('France', '+33', 'FR', 9, 9, 'https://flagcdn.com/w20/fr.png') ON DUPLICATE KEY UPDATE `phone_code` = '+33', `iso_code` = 'FR', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/fr.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Gabon', '+241', 'GA', 7, 8, 'https://flagcdn.com/w20/ga.png') ON DUPLICATE KEY UPDATE `phone_code` = '+241', `iso_code` = 'GA', `min_digits` = 7, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/ga.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Gambia', '+220', 'GM', 7, 7, 'https://flagcdn.com/w20/gm.png') ON DUPLICATE KEY UPDATE `phone_code` = '+220', `iso_code` = 'GM', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/gm.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Georgia', '+995', 'GE', 9, 9, 'https://flagcdn.com/w20/ge.png') ON DUPLICATE KEY UPDATE `phone_code` = '+995', `iso_code` = 'GE', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/ge.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Germany', '+49', 'DE', 10, 11, 'https://flagcdn.com/w20/de.png') ON DUPLICATE KEY UPDATE `phone_code` = '+49', `iso_code` = 'DE', `min_digits` = 10, `max_digits` = 11, `flag_url` = 'https://flagcdn.com/w20/de.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Ghana', '+233', 'GH', 9, 9, 'https://flagcdn.com/w20/gh.png') ON DUPLICATE KEY UPDATE `phone_code` = '+233', `iso_code` = 'GH', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/gh.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Greece', '+30', 'GR', 10, 10, 'https://flagcdn.com/w20/gr.png') ON DUPLICATE KEY UPDATE `phone_code` = '+30', `iso_code` = 'GR', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/gr.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Grenada', '+1', 'GD', 10, 10, 'https://flagcdn.com/w20/gd.png') ON DUPLICATE KEY UPDATE `phone_code` = '+1', `iso_code` = 'GD', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/gd.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Guatemala', '+502', 'GT', 8, 8, 'https://flagcdn.com/w20/gt.png') ON DUPLICATE KEY UPDATE `phone_code` = '+502', `iso_code` = 'GT', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/gt.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Guinea', '+224', 'GN', 9, 9, 'https://flagcdn.com/w20/gn.png') ON DUPLICATE KEY UPDATE `phone_code` = '+224', `iso_code` = 'GN', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/gn.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Guinea-Bissau', '+245', 'GW', 7, 7, 'https://flagcdn.com/w20/gw.png') ON DUPLICATE KEY UPDATE `phone_code` = '+245', `iso_code` = 'GW', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/gw.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Guyana', '+592', 'GY', 7, 7, 'https://flagcdn.com/w20/gy.png') ON DUPLICATE KEY UPDATE `phone_code` = '+592', `iso_code` = 'GY', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/gy.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Haiti', '+509', 'HT', 8, 8, 'https://flagcdn.com/w20/ht.png') ON DUPLICATE KEY UPDATE `phone_code` = '+509', `iso_code` = 'HT', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/ht.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Honduras', '+504', 'HN', 8, 8, 'https://flagcdn.com/w20/hn.png') ON DUPLICATE KEY UPDATE `phone_code` = '+504', `iso_code` = 'HN', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/hn.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Hungary', '+36', 'HU', 9, 9, 'https://flagcdn.com/w20/hu.png') ON DUPLICATE KEY UPDATE `phone_code` = '+36', `iso_code` = 'HU', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/hu.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Iceland', '+354', 'IS', 7, 7, 'https://flagcdn.com/w20/is.png') ON DUPLICATE KEY UPDATE `phone_code` = '+354', `iso_code` = 'IS', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/is.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Indonesia', '+62', 'ID', 9, 12, 'https://flagcdn.com/w20/id.png') ON DUPLICATE KEY UPDATE `phone_code` = '+62', `iso_code` = 'ID', `min_digits` = 9, `max_digits` = 12, `flag_url` = 'https://flagcdn.com/w20/id.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Iran', '+98', 'IR', 10, 10, 'https://flagcdn.com/w20/ir.png') ON DUPLICATE KEY UPDATE `phone_code` = '+98', `iso_code` = 'IR', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/ir.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Iraq', '+964', 'IQ', 10, 10, 'https://flagcdn.com/w20/iq.png') ON DUPLICATE KEY UPDATE `phone_code` = '+964', `iso_code` = 'IQ', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/iq.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Ireland', '+353', 'IE', 9, 9, 'https://flagcdn.com/w20/ie.png') ON DUPLICATE KEY UPDATE `phone_code` = '+353', `iso_code` = 'IE', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/ie.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Israel', '+972', 'IL', 9, 9, 'https://flagcdn.com/w20/il.png') ON DUPLICATE KEY UPDATE `phone_code` = '+972', `iso_code` = 'IL', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/il.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Italy', '+39', 'IT', 10, 10, 'https://flagcdn.com/w20/it.png') ON DUPLICATE KEY UPDATE `phone_code` = '+39', `iso_code` = 'IT', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/it.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Jamaica', '+1', 'JM', 10, 10, 'https://flagcdn.com/w20/jm.png') ON DUPLICATE KEY UPDATE `phone_code` = '+1', `iso_code` = 'JM', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/jm.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Japan', '+81', 'JP', 10, 10, 'https://flagcdn.com/w20/jp.png') ON DUPLICATE KEY UPDATE `phone_code` = '+81', `iso_code` = 'JP', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/jp.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Jordan', '+962', 'JO', 9, 9, 'https://flagcdn.com/w20/jo.png') ON DUPLICATE KEY UPDATE `phone_code` = '+962', `iso_code` = 'JO', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/jo.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Kazakhstan', '+7', 'KZ', 10, 10, 'https://flagcdn.com/w20/kz.png') ON DUPLICATE KEY UPDATE `phone_code` = '+7', `iso_code` = 'KZ', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/kz.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Kenya', '+254', 'KE', 9, 9, 'https://flagcdn.com/w20/ke.png') ON DUPLICATE KEY UPDATE `phone_code` = '+254', `iso_code` = 'KE', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/ke.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Kiribati', '+686', 'KI', 8, 8, 'https://flagcdn.com/w20/ki.png') ON DUPLICATE KEY UPDATE `phone_code` = '+686', `iso_code` = 'KI', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/ki.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Kuwait', '+965', 'KW', 8, 8, 'https://flagcdn.com/w20/kw.png') ON DUPLICATE KEY UPDATE `phone_code` = '+965', `iso_code` = 'KW', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/kw.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Kyrgyzstan', '+996', 'KG', 9, 9, 'https://flagcdn.com/w20/kg.png') ON DUPLICATE KEY UPDATE `phone_code` = '+996', `iso_code` = 'KG', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/kg.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Laos', '+856', 'LA', 9, 10, 'https://flagcdn.com/w20/la.png') ON DUPLICATE KEY UPDATE `phone_code` = '+856', `iso_code` = 'LA', `min_digits` = 9, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/la.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Latvia', '+371', 'LV', 8, 8, 'https://flagcdn.com/w20/lv.png') ON DUPLICATE KEY UPDATE `phone_code` = '+371', `iso_code` = 'LV', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/lv.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Lebanon', '+961', 'LB', 7, 8, 'https://flagcdn.com/w20/lb.png') ON DUPLICATE KEY UPDATE `phone_code` = '+961', `iso_code` = 'LB', `min_digits` = 7, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/lb.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Lesotho', '+266', 'LS', 8, 8, 'https://flagcdn.com/w20/ls.png') ON DUPLICATE KEY UPDATE `phone_code` = '+266', `iso_code` = 'LS', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/ls.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Liberia', '+231', 'LR', 8, 9, 'https://flagcdn.com/w20/lr.png') ON DUPLICATE KEY UPDATE `phone_code` = '+231', `iso_code` = 'LR', `min_digits` = 8, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/lr.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Libya', '+218', 'LY', 9, 9, 'https://flagcdn.com/w20/ly.png') ON DUPLICATE KEY UPDATE `phone_code` = '+218', `iso_code` = 'LY', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/ly.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Liechtenstein', '+423', 'LI', 7, 9, 'https://flagcdn.com/w20/li.png') ON DUPLICATE KEY UPDATE `phone_code` = '+423', `iso_code` = 'LI', `min_digits` = 7, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/li.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Lithuania', '+370', 'LT', 8, 8, 'https://flagcdn.com/w20/lt.png') ON DUPLICATE KEY UPDATE `phone_code` = '+370', `iso_code` = 'LT', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/lt.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Luxembourg', '+352', 'LU', 9, 9, 'https://flagcdn.com/w20/lu.png') ON DUPLICATE KEY UPDATE `phone_code` = '+352', `iso_code` = 'LU', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/lu.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Madagascar', '+261', 'MG', 9, 9, 'https://flagcdn.com/w20/mg.png') ON DUPLICATE KEY UPDATE `phone_code` = '+261', `iso_code` = 'MG', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/mg.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Malawi', '+265', 'MW', 9, 9, 'https://flagcdn.com/w20/mw.png') ON DUPLICATE KEY UPDATE `phone_code` = '+265', `iso_code` = 'MW', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/mw.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Malaysia', '+60', 'MY', 9, 10, 'https://flagcdn.com/w20/my.png') ON DUPLICATE KEY UPDATE `phone_code` = '+60', `iso_code` = 'MY', `min_digits` = 9, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/my.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Maldives', '+960', 'MV', 7, 7, 'https://flagcdn.com/w20/mv.png') ON DUPLICATE KEY UPDATE `phone_code` = '+960', `iso_code` = 'MV', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/mv.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Mali', '+223', 'ML', 8, 8, 'https://flagcdn.com/w20/ml.png') ON DUPLICATE KEY UPDATE `phone_code` = '+223', `iso_code` = 'ML', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/ml.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Malta', '+356', 'MT', 8, 8, 'https://flagcdn.com/w20/mt.png') ON DUPLICATE KEY UPDATE `phone_code` = '+356', `iso_code` = 'MT', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/mt.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Marshall Islands', '+692', 'MH', 7, 7, 'https://flagcdn.com/w20/mh.png') ON DUPLICATE KEY UPDATE `phone_code` = '+692', `iso_code` = 'MH', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/mh.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Mauritania', '+222', 'MR', 8, 8, 'https://flagcdn.com/w20/mr.png') ON DUPLICATE KEY UPDATE `phone_code` = '+222', `iso_code` = 'MR', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/mr.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Mauritius', '+230', 'MU', 8, 8, 'https://flagcdn.com/w20/mu.png') ON DUPLICATE KEY UPDATE `phone_code` = '+230', `iso_code` = 'MU', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/mu.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Mexico', '+52', 'MX', 10, 10, 'https://flagcdn.com/w20/mx.png') ON DUPLICATE KEY UPDATE `phone_code` = '+52', `iso_code` = 'MX', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/mx.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Micronesia', '+691', 'FM', 7, 7, 'https://flagcdn.com/w20/fm.png') ON DUPLICATE KEY UPDATE `phone_code` = '+691', `iso_code` = 'FM', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/fm.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Moldova', '+373', 'MD', 8, 8, 'https://flagcdn.com/w20/md.png') ON DUPLICATE KEY UPDATE `phone_code` = '+373', `iso_code` = 'MD', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/md.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Monaco', '+377', 'MC', 8, 9, 'https://flagcdn.com/w20/mc.png') ON DUPLICATE KEY UPDATE `phone_code` = '+377', `iso_code` = 'MC', `min_digits` = 8, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/mc.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Mongolia', '+976', 'MN', 8, 8, 'https://flagcdn.com/w20/mn.png') ON DUPLICATE KEY UPDATE `phone_code` = '+976', `iso_code` = 'MN', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/mn.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Montenegro', '+382', 'ME', 8, 8, 'https://flagcdn.com/w20/me.png') ON DUPLICATE KEY UPDATE `phone_code` = '+382', `iso_code` = 'ME', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/me.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Morocco', '+212', 'MA', 9, 9, 'https://flagcdn.com/w20/ma.png') ON DUPLICATE KEY UPDATE `phone_code` = '+212', `iso_code` = 'MA', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/ma.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Mozambique', '+258', 'MZ', 9, 9, 'https://flagcdn.com/w20/mz.png') ON DUPLICATE KEY UPDATE `phone_code` = '+258', `iso_code` = 'MZ', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/mz.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Myanmar', '+95', 'MM', 8, 10, 'https://flagcdn.com/w20/mm.png') ON DUPLICATE KEY UPDATE `phone_code` = '+95', `iso_code` = 'MM', `min_digits` = 8, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/mm.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Namibia', '+264', 'NA', 9, 9, 'https://flagcdn.com/w20/na.png') ON DUPLICATE KEY UPDATE `phone_code` = '+264', `iso_code` = 'NA', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/na.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Nauru', '+674', 'NR', 7, 7, 'https://flagcdn.com/w20/nr.png') ON DUPLICATE KEY UPDATE `phone_code` = '+674', `iso_code` = 'NR', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/nr.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Nepal', '+977', 'NP', 10, 10, 'https://flagcdn.com/w20/np.png') ON DUPLICATE KEY UPDATE `phone_code` = '+977', `iso_code` = 'NP', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/np.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Netherlands', '+31', 'NL', 9, 9, 'https://flagcdn.com/w20/nl.png') ON DUPLICATE KEY UPDATE `phone_code` = '+31', `iso_code` = 'NL', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/nl.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('New Zealand', '+64', 'NZ', 8, 10, 'https://flagcdn.com/w20/nz.png') ON DUPLICATE KEY UPDATE `phone_code` = '+64', `iso_code` = 'NZ', `min_digits` = 8, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/nz.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Nicaragua', '+505', 'NI', 8, 8, 'https://flagcdn.com/w20/ni.png') ON DUPLICATE KEY UPDATE `phone_code` = '+505', `iso_code` = 'NI', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/ni.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Niger', '+227', 'NE', 8, 8, 'https://flagcdn.com/w20/ne.png') ON DUPLICATE KEY UPDATE `phone_code` = '+227', `iso_code` = 'NE', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/ne.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Nigeria', '+234', 'NG', 10, 10, 'https://flagcdn.com/w20/ng.png') ON DUPLICATE KEY UPDATE `phone_code` = '+234', `iso_code` = 'NG', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/ng.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('North Korea', '+850', 'KP', 8, 10, 'https://flagcdn.com/w20/kp.png') ON DUPLICATE KEY UPDATE `phone_code` = '+850', `iso_code` = 'KP', `min_digits` = 8, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/kp.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('North Macedonia', '+389', 'MK', 8, 8, 'https://flagcdn.com/w20/mk.png') ON DUPLICATE KEY UPDATE `phone_code` = '+389', `iso_code` = 'MK', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/mk.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Norway', '+47', 'NO', 8, 8, 'https://flagcdn.com/w20/no.png') ON DUPLICATE KEY UPDATE `phone_code` = '+47', `iso_code` = 'NO', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/no.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Oman', '+968', 'OM', 8, 8, 'https://flagcdn.com/w20/om.png') ON DUPLICATE KEY UPDATE `phone_code` = '+968', `iso_code` = 'OM', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/om.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Pakistan', '+92', 'PK', 10, 10, 'https://flagcdn.com/w20/pk.png') ON DUPLICATE KEY UPDATE `phone_code` = '+92', `iso_code` = 'PK', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/pk.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Palau', '+680', 'PW', 7, 7, 'https://flagcdn.com/w20/pw.png') ON DUPLICATE KEY UPDATE `phone_code` = '+680', `iso_code` = 'PW', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/pw.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Panama', '+507', 'PA', 7, 8, 'https://flagcdn.com/w20/pa.png') ON DUPLICATE KEY UPDATE `phone_code` = '+507', `iso_code` = 'PA', `min_digits` = 7, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/pa.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Papua New Guinea', '+675', 'PG', 8, 8, 'https://flagcdn.com/w20/pg.png') ON DUPLICATE KEY UPDATE `phone_code` = '+675', `iso_code` = 'PG', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/pg.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Paraguay', '+595', 'PY', 9, 9, 'https://flagcdn.com/w20/py.png') ON DUPLICATE KEY UPDATE `phone_code` = '+595', `iso_code` = 'PY', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/py.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Peru', '+51', 'PE', 9, 9, 'https://flagcdn.com/w20/pe.png') ON DUPLICATE KEY UPDATE `phone_code` = '+51', `iso_code` = 'PE', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/pe.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Philippines', '+63', 'PH', 10, 10, 'https://flagcdn.com/w20/ph.png') ON DUPLICATE KEY UPDATE `phone_code` = '+63', `iso_code` = 'PH', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/ph.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Poland', '+48', 'PL', 9, 9, 'https://flagcdn.com/w20/pl.png') ON DUPLICATE KEY UPDATE `phone_code` = '+48', `iso_code` = 'PL', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/pl.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Portugal', '+351', 'PT', 9, 9, 'https://flagcdn.com/w20/pt.png') ON DUPLICATE KEY UPDATE `phone_code` = '+351', `iso_code` = 'PT', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/pt.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Qatar', '+974', 'QA', 8, 8, 'https://flagcdn.com/w20/qa.png') ON DUPLICATE KEY UPDATE `phone_code` = '+974', `iso_code` = 'QA', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/qa.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Romania', '+40', 'RO', 9, 10, 'https://flagcdn.com/w20/ro.png') ON DUPLICATE KEY UPDATE `phone_code` = '+40', `iso_code` = 'RO', `min_digits` = 9, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/ro.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Russia', '+7', 'RU', 10, 10, 'https://flagcdn.com/w20/ru.png') ON DUPLICATE KEY UPDATE `phone_code` = '+7', `iso_code` = 'RU', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/ru.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Rwanda', '+250', 'RW', 9, 9, 'https://flagcdn.com/w20/rw.png') ON DUPLICATE KEY UPDATE `phone_code` = '+250', `iso_code` = 'RW', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/rw.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Saint Kitts and Nevis', '+1', 'KN', 10, 10, 'https://flagcdn.com/w20/kn.png') ON DUPLICATE KEY UPDATE `phone_code` = '+1', `iso_code` = 'KN', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/kn.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Saint Lucia', '+1', 'LC', 10, 10, 'https://flagcdn.com/w20/lc.png') ON DUPLICATE KEY UPDATE `phone_code` = '+1', `iso_code` = 'LC', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/lc.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Saint Vincent and the Grenadines', '+1', 'VC', 10, 10, 'https://flagcdn.com/w20/vc.png') ON DUPLICATE KEY UPDATE `phone_code` = '+1', `iso_code` = 'VC', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/vc.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Samoa', '+685', 'WS', 7, 7, 'https://flagcdn.com/w20/ws.png') ON DUPLICATE KEY UPDATE `phone_code` = '+685', `iso_code` = 'WS', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/ws.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('San Marino', '+378', 'SM', 6, 10, 'https://flagcdn.com/w20/sm.png') ON DUPLICATE KEY UPDATE `phone_code` = '+378', `iso_code` = 'SM', `min_digits` = 6, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/sm.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Sao Tome and Principe', '+239', 'ST', 7, 7, 'https://flagcdn.com/w20/st.png') ON DUPLICATE KEY UPDATE `phone_code` = '+239', `iso_code` = 'ST', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/st.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Saudi Arabia', '+966', 'SA', 9, 9, 'https://flagcdn.com/w20/sa.png') ON DUPLICATE KEY UPDATE `phone_code` = '+966', `iso_code` = 'SA', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/sa.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Senegal', '+221', 'SN', 9, 9, 'https://flagcdn.com/w20/sn.png') ON DUPLICATE KEY UPDATE `phone_code` = '+221', `iso_code` = 'SN', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/sn.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Serbia', '+381', 'RS', 8, 9, 'https://flagcdn.com/w20/rs.png') ON DUPLICATE KEY UPDATE `phone_code` = '+381', `iso_code` = 'RS', `min_digits` = 8, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/rs.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Seychelles', '+248', 'SC', 7, 7, 'https://flagcdn.com/w20/sc.png') ON DUPLICATE KEY UPDATE `phone_code` = '+248', `iso_code` = 'SC', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/sc.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Sierra Leone', '+232', 'SL', 8, 8, 'https://flagcdn.com/w20/sl.png') ON DUPLICATE KEY UPDATE `phone_code` = '+232', `iso_code` = 'SL', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/sl.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Singapore', '+65', 'SG', 8, 8, 'https://flagcdn.com/w20/sg.png') ON DUPLICATE KEY UPDATE `phone_code` = '+65', `iso_code` = 'SG', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/sg.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Slovakia', '+421', 'SK', 9, 9, 'https://flagcdn.com/w20/sk.png') ON DUPLICATE KEY UPDATE `phone_code` = '+421', `iso_code` = 'SK', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/sk.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Slovenia', '+386', 'SI', 8, 8, 'https://flagcdn.com/w20/si.png') ON DUPLICATE KEY UPDATE `phone_code` = '+386', `iso_code` = 'SI', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/si.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Solomon Islands', '+677', 'SB', 7, 7, 'https://flagcdn.com/w20/sb.png') ON DUPLICATE KEY UPDATE `phone_code` = '+677', `iso_code` = 'SB', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/sb.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Somalia', '+252', 'SO', 8, 9, 'https://flagcdn.com/w20/so.png') ON DUPLICATE KEY UPDATE `phone_code` = '+252', `iso_code` = 'SO', `min_digits` = 8, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/so.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('South Africa', '+27', 'ZA', 9, 9, 'https://flagcdn.com/w20/za.png') ON DUPLICATE KEY UPDATE `phone_code` = '+27', `iso_code` = 'ZA', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/za.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('South Korea', '+82', 'KR', 9, 10, 'https://flagcdn.com/w20/kr.png') ON DUPLICATE KEY UPDATE `phone_code` = '+82', `iso_code` = 'KR', `min_digits` = 9, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/kr.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('South Sudan', '+211', 'SS', 9, 9, 'https://flagcdn.com/w20/ss.png') ON DUPLICATE KEY UPDATE `phone_code` = '+211', `iso_code` = 'SS', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/ss.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Spain', '+34', 'ES', 9, 9, 'https://flagcdn.com/w20/es.png') ON DUPLICATE KEY UPDATE `phone_code` = '+34', `iso_code` = 'ES', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/es.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Sri Lanka', '+94', 'LK', 9, 9, 'https://flagcdn.com/w20/lk.png') ON DUPLICATE KEY UPDATE `phone_code` = '+94', `iso_code` = 'LK', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/lk.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Sudan', '+249', 'SD', 9, 9, 'https://flagcdn.com/w20/sd.png') ON DUPLICATE KEY UPDATE `phone_code` = '+249', `iso_code` = 'SD', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/sd.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Suriname', '+597', 'SR', 7, 7, 'https://flagcdn.com/w20/sr.png') ON DUPLICATE KEY UPDATE `phone_code` = '+597', `iso_code` = 'SR', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/sr.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Sweden', '+46', 'SE', 9, 9, 'https://flagcdn.com/w20/se.png') ON DUPLICATE KEY UPDATE `phone_code` = '+46', `iso_code` = 'SE', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/se.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Switzerland', '+41', 'CH', 9, 9, 'https://flagcdn.com/w20/ch.png') ON DUPLICATE KEY UPDATE `phone_code` = '+41', `iso_code` = 'CH', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/ch.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Syria', '+963', 'SY', 9, 9, 'https://flagcdn.com/w20/sy.png') ON DUPLICATE KEY UPDATE `phone_code` = '+963', `iso_code` = 'SY', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/sy.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Taiwan', '+886', 'TW', 9, 9, 'https://flagcdn.com/w20/tw.png') ON DUPLICATE KEY UPDATE `phone_code` = '+886', `iso_code` = 'TW', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/tw.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Tajikistan', '+992', 'TJ', 9, 9, 'https://flagcdn.com/w20/tj.png') ON DUPLICATE KEY UPDATE `phone_code` = '+992', `iso_code` = 'TJ', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/tj.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Tanzania', '+255', 'TZ', 9, 9, 'https://flagcdn.com/w20/tz.png') ON DUPLICATE KEY UPDATE `phone_code` = '+255', `iso_code` = 'TZ', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/tz.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Thailand', '+66', 'TH', 9, 9, 'https://flagcdn.com/w20/th.png') ON DUPLICATE KEY UPDATE `phone_code` = '+66', `iso_code` = 'TH', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/th.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Timor-Leste', '+670', 'TL', 8, 8, 'https://flagcdn.com/w20/tl.png') ON DUPLICATE KEY UPDATE `phone_code` = '+670', `iso_code` = 'TL', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/tl.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Togo', '+228', 'TG', 8, 8, 'https://flagcdn.com/w20/tg.png') ON DUPLICATE KEY UPDATE `phone_code` = '+228', `iso_code` = 'TG', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/tg.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Tonga', '+676', 'TO', 7, 7, 'https://flagcdn.com/w20/to.png') ON DUPLICATE KEY UPDATE `phone_code` = '+676', `iso_code` = 'TO', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/to.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Trinidad and Tobago', '+1', 'TT', 10, 10, 'https://flagcdn.com/w20/tt.png') ON DUPLICATE KEY UPDATE `phone_code` = '+1', `iso_code` = 'TT', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/tt.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Tunisia', '+216', 'TN', 8, 8, 'https://flagcdn.com/w20/tn.png') ON DUPLICATE KEY UPDATE `phone_code` = '+216', `iso_code` = 'TN', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/tn.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Turkey', '+90', 'TR', 10, 10, 'https://flagcdn.com/w20/tr.png') ON DUPLICATE KEY UPDATE `phone_code` = '+90', `iso_code` = 'TR', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/tr.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Turkmenistan', '+993', 'TM', 8, 8, 'https://flagcdn.com/w20/tm.png') ON DUPLICATE KEY UPDATE `phone_code` = '+993', `iso_code` = 'TM', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/tm.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Tuvalu', '+688', 'TV', 7, 7, 'https://flagcdn.com/w20/tv.png') ON DUPLICATE KEY UPDATE `phone_code` = '+688', `iso_code` = 'TV', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/tv.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Uganda', '+256', 'UG', 9, 9, 'https://flagcdn.com/w20/ug.png') ON DUPLICATE KEY UPDATE `phone_code` = '+256', `iso_code` = 'UG', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/ug.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Ukraine', '+380', 'UA', 9, 9, 'https://flagcdn.com/w20/ua.png') ON DUPLICATE KEY UPDATE `phone_code` = '+380', `iso_code` = 'UA', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/ua.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('United Arab Emirates', '+971', 'AE', 9, 9, 'https://flagcdn.com/w20/ae.png') ON DUPLICATE KEY UPDATE `phone_code` = '+971', `iso_code` = 'AE', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/ae.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('United Kingdom', '+44', 'GB', 10, 11, 'https://flagcdn.com/w20/gb.png') ON DUPLICATE KEY UPDATE `phone_code` = '+44', `iso_code` = 'GB', `min_digits` = 10, `max_digits` = 11, `flag_url` = 'https://flagcdn.com/w20/gb.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('United States', '+1', 'US', 10, 10, 'https://flagcdn.com/w20/us.png') ON DUPLICATE KEY UPDATE `phone_code` = '+1', `iso_code` = 'US', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/us.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Uruguay', '+598', 'UY', 8, 8, 'https://flagcdn.com/w20/uy.png') ON DUPLICATE KEY UPDATE `phone_code` = '+598', `iso_code` = 'UY', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/uy.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Uzbekistan', '+998', 'UZ', 9, 9, 'https://flagcdn.com/w20/uz.png') ON DUPLICATE KEY UPDATE `phone_code` = '+998', `iso_code` = 'UZ', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/uz.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Vanuatu', '+678', 'VU', 7, 7, 'https://flagcdn.com/w20/vu.png') ON DUPLICATE KEY UPDATE `phone_code` = '+678', `iso_code` = 'VU', `min_digits` = 7, `max_digits` = 7, `flag_url` = 'https://flagcdn.com/w20/vu.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Vatican City', '+379', 'VA', 8, 8, 'https://flagcdn.com/w20/va.png') ON DUPLICATE KEY UPDATE `phone_code` = '+379', `iso_code` = 'VA', `min_digits` = 8, `max_digits` = 8, `flag_url` = 'https://flagcdn.com/w20/va.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Venezuela', '+58', 'VE', 10, 10, 'https://flagcdn.com/w20/ve.png') ON DUPLICATE KEY UPDATE `phone_code` = '+58', `iso_code` = 'VE', `min_digits` = 10, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/ve.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Vietnam', '+84', 'VN', 9, 10, 'https://flagcdn.com/w20/vn.png') ON DUPLICATE KEY UPDATE `phone_code` = '+84', `iso_code` = 'VN', `min_digits` = 9, `max_digits` = 10, `flag_url` = 'https://flagcdn.com/w20/vn.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Yemen', '+967', 'YE', 9, 9, 'https://flagcdn.com/w20/ye.png') ON DUPLICATE KEY UPDATE `phone_code` = '+967', `iso_code` = 'YE', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/ye.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Zambia', '+260', 'ZM', 9, 9, 'https://flagcdn.com/w20/zm.png') ON DUPLICATE KEY UPDATE `phone_code` = '+260', `iso_code` = 'ZM', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/zm.png';
INSERT INTO `countries` (`name`, `phone_code`, `iso_code`, `min_digits`, `max_digits`, `flag_url`) VALUES ('Zimbabwe', '+263', 'ZW', 9, 9, 'https://flagcdn.com/w20/zw.png') ON DUPLICATE KEY UPDATE `phone_code` = '+263', `iso_code` = 'ZW', `min_digits` = 9, `max_digits` = 9, `flag_url` = 'https://flagcdn.com/w20/zw.png';
