<?php

namespace App\Support;

class CountryPhone
{
    public static function meta(string $countryName): array
    {
        $map = self::map();
        return $map[$countryName] ?? ['dial_code' => '+91', 'iso' => 'in'];
    }

    public static function map(): array
    {
        return [
            'Afghanistan' => ['dial_code' => '+93', 'iso' => 'af'],
            'Albania' => ['dial_code' => '+355', 'iso' => 'al'],
            'Algeria' => ['dial_code' => '+213', 'iso' => 'dz'],
            'Andorra' => ['dial_code' => '+376', 'iso' => 'ad'],
            'Angola' => ['dial_code' => '+244', 'iso' => 'ao'],
            'Argentina' => ['dial_code' => '+54', 'iso' => 'ar'],
            'Armenia' => ['dial_code' => '+374', 'iso' => 'am'],
            'Australia' => ['dial_code' => '+61', 'iso' => 'au'],
            'Austria' => ['dial_code' => '+43', 'iso' => 'at'],
            'Azerbaijan' => ['dial_code' => '+994', 'iso' => 'az'],
            'Bahamas' => ['dial_code' => '+1', 'iso' => 'bs'],
            'Bahrain' => ['dial_code' => '+973', 'iso' => 'bh'],
            'Bangladesh' => ['dial_code' => '+880', 'iso' => 'bd'],
            'Barbados' => ['dial_code' => '+1', 'iso' => 'bb'],
            'Belarus' => ['dial_code' => '+375', 'iso' => 'by'],
            'Belgium' => ['dial_code' => '+32', 'iso' => 'be'],
            'Belize' => ['dial_code' => '+501', 'iso' => 'bz'],
            'Benin' => ['dial_code' => '+229', 'iso' => 'bj'],
            'Bhutan' => ['dial_code' => '+975', 'iso' => 'bt'],
            'Bolivia' => ['dial_code' => '+591', 'iso' => 'bo'],
            'Bosnia and Herzegovina' => ['dial_code' => '+387', 'iso' => 'ba'],
            'Botswana' => ['dial_code' => '+267', 'iso' => 'bw'],
            'Brazil' => ['dial_code' => '+55', 'iso' => 'br'],
            'Brunei' => ['dial_code' => '+673', 'iso' => 'bn'],
            'Bulgaria' => ['dial_code' => '+359', 'iso' => 'bg'],
            'Burkina Faso' => ['dial_code' => '+226', 'iso' => 'bf'],
            'Burundi' => ['dial_code' => '+257', 'iso' => 'bi'],
            'Cambodia' => ['dial_code' => '+855', 'iso' => 'kh'],
            'Cameroon' => ['dial_code' => '+237', 'iso' => 'cm'],
            'Canada' => ['dial_code' => '+1', 'iso' => 'ca'],
            'Cape Verde' => ['dial_code' => '+238', 'iso' => 'cv'],
            'Central African Republic' => ['dial_code' => '+236', 'iso' => 'cf'],
            'Chad' => ['dial_code' => '+235', 'iso' => 'td'],
            'Chile' => ['dial_code' => '+56', 'iso' => 'cl'],
            'China' => ['dial_code' => '+86', 'iso' => 'cn'],
            'Colombia' => ['dial_code' => '+57', 'iso' => 'co'],
            'Comoros' => ['dial_code' => '+269', 'iso' => 'km'],
            'Congo' => ['dial_code' => '+242', 'iso' => 'cg'],
            'Congo (Brazzaville)' => ['dial_code' => '+242', 'iso' => 'cg'],
            'Congo (Kinshasa)' => ['dial_code' => '+243', 'iso' => 'cd'],
            'Costa Rica' => ['dial_code' => '+506', 'iso' => 'cr'],
            'Croatia' => ['dial_code' => '+385', 'iso' => 'hr'],
            'Cuba' => ['dial_code' => '+53', 'iso' => 'cu'],
            'Cyprus' => ['dial_code' => '+357', 'iso' => 'cy'],
            'Czech Republic' => ['dial_code' => '+420', 'iso' => 'cz'],
            'Denmark' => ['dial_code' => '+45', 'iso' => 'dk'],
            'Djibouti' => ['dial_code' => '+253', 'iso' => 'dj'],
            'Dominica' => ['dial_code' => '+1', 'iso' => 'dm'],
            'Dominican Republic' => ['dial_code' => '+1', 'iso' => 'do'],
            'Ecuador' => ['dial_code' => '+593', 'iso' => 'ec'],
            'Egypt' => ['dial_code' => '+20', 'iso' => 'eg'],
            'El Salvador' => ['dial_code' => '+503', 'iso' => 'sv'],
            'Equatorial Guinea' => ['dial_code' => '+240', 'iso' => 'gq'],
            'Eritrea' => ['dial_code' => '+291', 'iso' => 'er'],
            'Estonia' => ['dial_code' => '+372', 'iso' => 'ee'],
            'Eswatini' => ['dial_code' => '+268', 'iso' => 'sz'],
            'Ethiopia' => ['dial_code' => '+251', 'iso' => 'et'],
            'Fiji' => ['dial_code' => '+679', 'iso' => 'fj'],
            'Finland' => ['dial_code' => '+358', 'iso' => 'fi'],
            'France' => ['dial_code' => '+33', 'iso' => 'fr'],
            'Gabon' => ['dial_code' => '+241', 'iso' => 'ga'],
            'Gambia' => ['dial_code' => '+220', 'iso' => 'gm'],
            'Georgia' => ['dial_code' => '+995', 'iso' => 'ge'],
            'Germany' => ['dial_code' => '+49', 'iso' => 'de'],
            'Ghana' => ['dial_code' => '+233', 'iso' => 'gh'],
            'Greece' => ['dial_code' => '+30', 'iso' => 'gr'],
            'Grenada' => ['dial_code' => '+1', 'iso' => 'gd'],
            'Guatemala' => ['dial_code' => '+502', 'iso' => 'gt'],
            'Guinea' => ['dial_code' => '+224', 'iso' => 'gn'],
            'Guinea-Bissau' => ['dial_code' => '+245', 'iso' => 'gw'],
            'Guyana' => ['dial_code' => '+592', 'iso' => 'gy'],
            'Haiti' => ['dial_code' => '+509', 'iso' => 'ht'],
            'Honduras' => ['dial_code' => '+504', 'iso' => 'hn'],
            'Hungary' => ['dial_code' => '+36', 'iso' => 'hu'],
            'Iceland' => ['dial_code' => '+354', 'iso' => 'is'],
            'India' => ['dial_code' => '+91', 'iso' => 'in'],
            'Indonesia' => ['dial_code' => '+62', 'iso' => 'id'],
            'Iran' => ['dial_code' => '+98', 'iso' => 'ir'],
            'Iraq' => ['dial_code' => '+964', 'iso' => 'iq'],
            'Ireland' => ['dial_code' => '+353', 'iso' => 'ie'],
            'Israel' => ['dial_code' => '+972', 'iso' => 'il'],
            'Italy' => ['dial_code' => '+39', 'iso' => 'it'],
            'Jamaica' => ['dial_code' => '+1', 'iso' => 'jm'],
            'Japan' => ['dial_code' => '+81', 'iso' => 'jp'],
            'Jordan' => ['dial_code' => '+962', 'iso' => 'jo'],
            'Kazakhstan' => ['dial_code' => '+7', 'iso' => 'kz'],
            'Kenya' => ['dial_code' => '+254', 'iso' => 'ke'],
            'Kiribati' => ['dial_code' => '+686', 'iso' => 'ki'],
            'Kuwait' => ['dial_code' => '+965', 'iso' => 'kw'],
            'Kyrgyzstan' => ['dial_code' => '+996', 'iso' => 'kg'],
            'Laos' => ['dial_code' => '+856', 'iso' => 'la'],
            'Latvia' => ['dial_code' => '+371', 'iso' => 'lv'],
            'Lebanon' => ['dial_code' => '+961', 'iso' => 'lb'],
            'Lesotho' => ['dial_code' => '+266', 'iso' => 'ls'],
            'Liberia' => ['dial_code' => '+231', 'iso' => 'lr'],
            'Libya' => ['dial_code' => '+218', 'iso' => 'ly'],
            'Liechtenstein' => ['dial_code' => '+423', 'iso' => 'li'],
            'Lithuania' => ['dial_code' => '+370', 'iso' => 'lt'],
            'Luxembourg' => ['dial_code' => '+352', 'iso' => 'lu'],
            'Madagascar' => ['dial_code' => '+261', 'iso' => 'mg'],
            'Malawi' => ['dial_code' => '+265', 'iso' => 'mw'],
            'Malaysia' => ['dial_code' => '+60', 'iso' => 'my'],
            'Maldives' => ['dial_code' => '+960', 'iso' => 'mv'],
            'Mali' => ['dial_code' => '+223', 'iso' => 'ml'],
            'Malta' => ['dial_code' => '+356', 'iso' => 'mt'],
            'Marshall Islands' => ['dial_code' => '+692', 'iso' => 'mh'],
            'Mauritania' => ['dial_code' => '+222', 'iso' => 'mr'],
            'Mauritius' => ['dial_code' => '+230', 'iso' => 'mu'],
            'Mexico' => ['dial_code' => '+52', 'iso' => 'mx'],
            'Micronesia' => ['dial_code' => '+691', 'iso' => 'fm'],
            'Moldova' => ['dial_code' => '+373', 'iso' => 'md'],
            'Monaco' => ['dial_code' => '+377', 'iso' => 'mc'],
            'Mongolia' => ['dial_code' => '+976', 'iso' => 'mn'],
            'Montenegro' => ['dial_code' => '+382', 'iso' => 'me'],
            'Morocco' => ['dial_code' => '+212', 'iso' => 'ma'],
            'Mozambique' => ['dial_code' => '+258', 'iso' => 'mz'],
            'Myanmar' => ['dial_code' => '+95', 'iso' => 'mm'],
            'Namibia' => ['dial_code' => '+264', 'iso' => 'na'],
            'Nauru' => ['dial_code' => '+674', 'iso' => 'nr'],
            'Nepal' => ['dial_code' => '+977', 'iso' => 'np'],
            'Netherlands' => ['dial_code' => '+31', 'iso' => 'nl'],
            'New Zealand' => ['dial_code' => '+64', 'iso' => 'nz'],
            'Nicaragua' => ['dial_code' => '+505', 'iso' => 'ni'],
            'Niger' => ['dial_code' => '+227', 'iso' => 'ne'],
            'Nigeria' => ['dial_code' => '+234', 'iso' => 'ng'],
            'North Korea' => ['dial_code' => '+850', 'iso' => 'kp'],
            'North Macedonia' => ['dial_code' => '+389', 'iso' => 'mk'],
            'Norway' => ['dial_code' => '+47', 'iso' => 'no'],
            'Oman' => ['dial_code' => '+968', 'iso' => 'om'],
            'Pakistan' => ['dial_code' => '+92', 'iso' => 'pk'],
            'Palau' => ['dial_code' => '+680', 'iso' => 'pw'],
            'Panama' => ['dial_code' => '+507', 'iso' => 'pa'],
            'Papua New Guinea' => ['dial_code' => '+675', 'iso' => 'pg'],
            'Paraguay' => ['dial_code' => '+595', 'iso' => 'py'],
            'Peru' => ['dial_code' => '+51', 'iso' => 'pe'],
            'Philippines' => ['dial_code' => '+63', 'iso' => 'ph'],
            'Poland' => ['dial_code' => '+48', 'iso' => 'pl'],
            'Portugal' => ['dial_code' => '+351', 'iso' => 'pt'],
            'Qatar' => ['dial_code' => '+974', 'iso' => 'qa'],
            'Romania' => ['dial_code' => '+40', 'iso' => 'ro'],
            'Russia' => ['dial_code' => '+7', 'iso' => 'ru'],
            'Rwanda' => ['dial_code' => '+250', 'iso' => 'rw'],
            'Saint Kitts and Nevis' => ['dial_code' => '+1', 'iso' => 'kn'],
            'Saint Lucia' => ['dial_code' => '+1', 'iso' => 'lc'],
            'Saint Vincent and the Grenadines' => ['dial_code' => '+1', 'iso' => 'vc'],
            'Samoa' => ['dial_code' => '+685', 'iso' => 'ws'],
            'San Marino' => ['dial_code' => '+378', 'iso' => 'sm'],
            'Sao Tome and Principe' => ['dial_code' => '+239', 'iso' => 'st'],
            'Saudi Arabia' => ['dial_code' => '+966', 'iso' => 'sa'],
            'Senegal' => ['dial_code' => '+221', 'iso' => 'sn'],
            'Serbia' => ['dial_code' => '+381', 'iso' => 'rs'],
            'Seychelles' => ['dial_code' => '+248', 'iso' => 'sc'],
            'Sierra Leone' => ['dial_code' => '+232', 'iso' => 'sl'],
            'Singapore' => ['dial_code' => '+65', 'iso' => 'sg'],
            'Slovakia' => ['dial_code' => '+421', 'iso' => 'sk'],
            'Slovenia' => ['dial_code' => '+386', 'iso' => 'si'],
            'Solomon Islands' => ['dial_code' => '+677', 'iso' => 'sb'],
            'Somalia' => ['dial_code' => '+252', 'iso' => 'so'],
            'South Africa' => ['dial_code' => '+27', 'iso' => 'za'],
            'South Korea' => ['dial_code' => '+82', 'iso' => 'kr'],
            'South Sudan' => ['dial_code' => '+211', 'iso' => 'ss'],
            'Spain' => ['dial_code' => '+34', 'iso' => 'es'],
            'Sri Lanka' => ['dial_code' => '+94', 'iso' => 'lk'],
            'Sudan' => ['dial_code' => '+249', 'iso' => 'sd'],
            'Suriname' => ['dial_code' => '+597', 'iso' => 'sr'],
            'Sweden' => ['dial_code' => '+46', 'iso' => 'se'],
            'Switzerland' => ['dial_code' => '+41', 'iso' => 'ch'],
            'Syria' => ['dial_code' => '+963', 'iso' => 'sy'],
            'Taiwan' => ['dial_code' => '+886', 'iso' => 'tw'],
            'Tajikistan' => ['dial_code' => '+992', 'iso' => 'tj'],
            'Tanzania' => ['dial_code' => '+255', 'iso' => 'tz'],
            'Thailand' => ['dial_code' => '+66', 'iso' => 'th'],
            'Timor-Leste' => ['dial_code' => '+670', 'iso' => 'tl'],
            'Togo' => ['dial_code' => '+228', 'iso' => 'tg'],
            'Tonga' => ['dial_code' => '+676', 'iso' => 'to'],
            'Trinidad and Tobago' => ['dial_code' => '+1', 'iso' => 'tt'],
            'Tunisia' => ['dial_code' => '+216', 'iso' => 'tn'],
            'Turkey' => ['dial_code' => '+90', 'iso' => 'tr'],
            'Turkmenistan' => ['dial_code' => '+993', 'iso' => 'tm'],
            'Tuvalu' => ['dial_code' => '+688', 'iso' => 'tv'],
            'Uganda' => ['dial_code' => '+256', 'iso' => 'ug'],
            'Ukraine' => ['dial_code' => '+380', 'iso' => 'ua'],
            'United Arab Emirates' => ['dial_code' => '+971', 'iso' => 'ae'],
            'United Kingdom' => ['dial_code' => '+44', 'iso' => 'gb'],
            'United States' => ['dial_code' => '+1', 'iso' => 'us'],
            'Uruguay' => ['dial_code' => '+598', 'iso' => 'uy'],
            'Uzbekistan' => ['dial_code' => '+998', 'iso' => 'uz'],
            'Vanuatu' => ['dial_code' => '+678', 'iso' => 'vu'],
            'Vatican City' => ['dial_code' => '+379', 'iso' => 'va'],
            'Venezuela' => ['dial_code' => '+58', 'iso' => 've'],
            'Vietnam' => ['dial_code' => '+84', 'iso' => 'vn'],
            'Yemen' => ['dial_code' => '+967', 'iso' => 'ye'],
            'Zambia' => ['dial_code' => '+260', 'iso' => 'zm'],
            'Zimbabwe' => ['dial_code' => '+263', 'iso' => 'zw'],
        ];
    }
}
