<?php

namespace App\Support;

class CountryPhone
{
    public static function meta(string $countryName): array
    {
        $map = self::map();
        return $map[$countryName] ?? ['dial_code' => '+91', 'iso' => 'in', 'min_digits' => 10, 'max_digits' => 10];
    }

    public static function findByDialCode(string $dialCode): ?array
    {
        $map = self::map();
        foreach ($map as $name => $data) {
            if ($data['dial_code'] === $dialCode) {
                return array_merge($data, ['name' => $name]);
            }
        }
        return null;
    }

    public static function getDigitRules(string $countryOrCode): array
    {
        $map = self::map();
        if (isset($map[$countryOrCode])) {
            return array_merge($map[$countryOrCode], ['name' => $countryOrCode]);
        }

        foreach ($map as $name => $data) {
            if ($data['dial_code'] === $countryOrCode) {
                return array_merge($data, ['name' => $name]);
            }
        }

        return ['dial_code' => '+91', 'iso' => 'in', 'min_digits' => 6, 'max_digits' => 15, 'name' => 'Default'];
    }

    public static function map(): array
    {
        return [
            'Afghanistan' => ['dial_code' => '+93', 'iso' => 'af', 'min_digits' => 9, 'max_digits' => 9],
            'Albania' => ['dial_code' => '+355', 'iso' => 'al', 'min_digits' => 9, 'max_digits' => 9],
            'Algeria' => ['dial_code' => '+213', 'iso' => 'dz', 'min_digits' => 9, 'max_digits' => 9],
            'Andorra' => ['dial_code' => '+376', 'iso' => 'ad', 'min_digits' => 6, 'max_digits' => 9],
            'Angola' => ['dial_code' => '+244', 'iso' => 'ao', 'min_digits' => 9, 'max_digits' => 9],
            'Argentina' => ['dial_code' => '+54', 'iso' => 'ar', 'min_digits' => 10, 'max_digits' => 10],
            'Armenia' => ['dial_code' => '+374', 'iso' => 'am', 'min_digits' => 8, 'max_digits' => 8],
            'Australia' => ['dial_code' => '+61', 'iso' => 'au', 'min_digits' => 9, 'max_digits' => 9],
            'Austria' => ['dial_code' => '+43', 'iso' => 'at', 'min_digits' => 10, 'max_digits' => 11],
            'Azerbaijan' => ['dial_code' => '+994', 'iso' => 'az', 'min_digits' => 9, 'max_digits' => 9],
            'Bahamas' => ['dial_code' => '+1', 'iso' => 'bs', 'min_digits' => 10, 'max_digits' => 10],
            'Bahrain' => ['dial_code' => '+973', 'iso' => 'bh', 'min_digits' => 8, 'max_digits' => 8],
            'Bangladesh' => ['dial_code' => '+880', 'iso' => 'bd', 'min_digits' => 10, 'max_digits' => 10],
            'Barbados' => ['dial_code' => '+1', 'iso' => 'bb', 'min_digits' => 10, 'max_digits' => 10],
            'Belarus' => ['dial_code' => '+375', 'iso' => 'by', 'min_digits' => 9, 'max_digits' => 9],
            'Belgium' => ['dial_code' => '+32', 'iso' => 'be', 'min_digits' => 9, 'max_digits' => 9],
            'Belize' => ['dial_code' => '+501', 'iso' => 'bz', 'min_digits' => 7, 'max_digits' => 7],
            'Benin' => ['dial_code' => '+229', 'iso' => 'bj', 'min_digits' => 8, 'max_digits' => 8],
            'Bhutan' => ['dial_code' => '+975', 'iso' => 'bt', 'min_digits' => 8, 'max_digits' => 8],
            'Bolivia' => ['dial_code' => '+591', 'iso' => 'bo', 'min_digits' => 8, 'max_digits' => 8],
            'Bosnia and Herzegovina' => ['dial_code' => '+387', 'iso' => 'ba', 'min_digits' => 8, 'max_digits' => 8],
            'Botswana' => ['dial_code' => '+267', 'iso' => 'bw', 'min_digits' => 8, 'max_digits' => 8],
            'Brazil' => ['dial_code' => '+55', 'iso' => 'br', 'min_digits' => 10, 'max_digits' => 11],
            'Brunei' => ['dial_code' => '+673', 'iso' => 'bn', 'min_digits' => 7, 'max_digits' => 7],
            'Bulgaria' => ['dial_code' => '+359', 'iso' => 'bg', 'min_digits' => 9, 'max_digits' => 9],
            'Burkina Faso' => ['dial_code' => '+226', 'iso' => 'bf', 'min_digits' => 8, 'max_digits' => 8],
            'Burundi' => ['dial_code' => '+257', 'iso' => 'bi', 'min_digits' => 8, 'max_digits' => 8],
            'Cambodia' => ['dial_code' => '+855', 'iso' => 'kh', 'min_digits' => 8, 'max_digits' => 9],
            'Cameroon' => ['dial_code' => '+237', 'iso' => 'cm', 'min_digits' => 9, 'max_digits' => 9],
            'Canada' => ['dial_code' => '+1', 'iso' => 'ca', 'min_digits' => 10, 'max_digits' => 10],
            'Cape Verde' => ['dial_code' => '+238', 'iso' => 'cv', 'min_digits' => 7, 'max_digits' => 7],
            'Central African Republic' => ['dial_code' => '+236', 'iso' => 'cf', 'min_digits' => 8, 'max_digits' => 8],
            'Chad' => ['dial_code' => '+235', 'iso' => 'td', 'min_digits' => 8, 'max_digits' => 8],
            'Chile' => ['dial_code' => '+56', 'iso' => 'cl', 'min_digits' => 9, 'max_digits' => 9],
            'China' => ['dial_code' => '+86', 'iso' => 'cn', 'min_digits' => 11, 'max_digits' => 11],
            'Colombia' => ['dial_code' => '+57', 'iso' => 'co', 'min_digits' => 10, 'max_digits' => 10],
            'Comoros' => ['dial_code' => '+269', 'iso' => 'km', 'min_digits' => 7, 'max_digits' => 7],
            'Congo' => ['dial_code' => '+242', 'iso' => 'cg', 'min_digits' => 9, 'max_digits' => 9],
            'Congo (Brazzaville)' => ['dial_code' => '+242', 'iso' => 'cg', 'min_digits' => 9, 'max_digits' => 9],
            'Congo (Kinshasa)' => ['dial_code' => '+243', 'iso' => 'cd', 'min_digits' => 9, 'max_digits' => 9],
            'Costa Rica' => ['dial_code' => '+506', 'iso' => 'cr', 'min_digits' => 8, 'max_digits' => 8],
            'Croatia' => ['dial_code' => '+385', 'iso' => 'hr', 'min_digits' => 8, 'max_digits' => 9],
            'Cuba' => ['dial_code' => '+53', 'iso' => 'cu', 'min_digits' => 8, 'max_digits' => 8],
            'Cyprus' => ['dial_code' => '+357', 'iso' => 'cy', 'min_digits' => 8, 'max_digits' => 8],
            'Czech Republic' => ['dial_code' => '+420', 'iso' => 'cz', 'min_digits' => 9, 'max_digits' => 9],
            'Denmark' => ['dial_code' => '+45', 'iso' => 'dk', 'min_digits' => 8, 'max_digits' => 8],
            'Djibouti' => ['dial_code' => '+253', 'iso' => 'dj', 'min_digits' => 8, 'max_digits' => 8],
            'Dominica' => ['dial_code' => '+1', 'iso' => 'dm', 'min_digits' => 10, 'max_digits' => 10],
            'Dominican Republic' => ['dial_code' => '+1', 'iso' => 'do', 'min_digits' => 10, 'max_digits' => 10],
            'Ecuador' => ['dial_code' => '+593', 'iso' => 'ec', 'min_digits' => 9, 'max_digits' => 9],
            'Egypt' => ['dial_code' => '+20', 'iso' => 'eg', 'min_digits' => 10, 'max_digits' => 10],
            'El Salvador' => ['dial_code' => '+503', 'iso' => 'sv', 'min_digits' => 8, 'max_digits' => 8],
            'Equatorial Guinea' => ['dial_code' => '+240', 'iso' => 'gq', 'min_digits' => 9, 'max_digits' => 9],
            'Eritrea' => ['dial_code' => '+291', 'iso' => 'er', 'min_digits' => 7, 'max_digits' => 7],
            'Estonia' => ['dial_code' => '+372', 'iso' => 'ee', 'min_digits' => 7, 'max_digits' => 8],
            'Eswatini' => ['dial_code' => '+268', 'iso' => 'sz', 'min_digits' => 8, 'max_digits' => 8],
            'Ethiopia' => ['dial_code' => '+251', 'iso' => 'et', 'min_digits' => 9, 'max_digits' => 9],
            'Fiji' => ['dial_code' => '+679', 'iso' => 'fj', 'min_digits' => 7, 'max_digits' => 7],
            'Finland' => ['dial_code' => '+358', 'iso' => 'fi', 'min_digits' => 9, 'max_digits' => 10],
            'France' => ['dial_code' => '+33', 'iso' => 'fr', 'min_digits' => 9, 'max_digits' => 9],
            'Gabon' => ['dial_code' => '+241', 'iso' => 'ga', 'min_digits' => 7, 'max_digits' => 8],
            'Gambia' => ['dial_code' => '+220', 'iso' => 'gm', 'min_digits' => 7, 'max_digits' => 7],
            'Georgia' => ['dial_code' => '+995', 'iso' => 'ge', 'min_digits' => 9, 'max_digits' => 9],
            'Germany' => ['dial_code' => '+49', 'iso' => 'de', 'min_digits' => 10, 'max_digits' => 11],
            'Ghana' => ['dial_code' => '+233', 'iso' => 'gh', 'min_digits' => 9, 'max_digits' => 9],
            'Greece' => ['dial_code' => '+30', 'iso' => 'gr', 'min_digits' => 10, 'max_digits' => 10],
            'Grenada' => ['dial_code' => '+1', 'iso' => 'gd', 'min_digits' => 10, 'max_digits' => 10],
            'Guatemala' => ['dial_code' => '+502', 'iso' => 'gt', 'min_digits' => 8, 'max_digits' => 8],
            'Guinea' => ['dial_code' => '+224', 'iso' => 'gn', 'min_digits' => 9, 'max_digits' => 9],
            'Guinea-Bissau' => ['dial_code' => '+245', 'iso' => 'gw', 'min_digits' => 7, 'max_digits' => 7],
            'Guyana' => ['dial_code' => '+592', 'iso' => 'gy', 'min_digits' => 7, 'max_digits' => 7],
            'Haiti' => ['dial_code' => '+509', 'iso' => 'ht', 'min_digits' => 8, 'max_digits' => 8],
            'Honduras' => ['dial_code' => '+504', 'iso' => 'hn', 'min_digits' => 8, 'max_digits' => 8],
            'Hungary' => ['dial_code' => '+36', 'iso' => 'hu', 'min_digits' => 9, 'max_digits' => 9],
            'Iceland' => ['dial_code' => '+354', 'iso' => 'is', 'min_digits' => 7, 'max_digits' => 7],
            'India' => ['dial_code' => '+91', 'iso' => 'in', 'min_digits' => 10, 'max_digits' => 10],
            'Indonesia' => ['dial_code' => '+62', 'iso' => 'id', 'min_digits' => 9, 'max_digits' => 12],
            'Iran' => ['dial_code' => '+98', 'iso' => 'ir', 'min_digits' => 10, 'max_digits' => 10],
            'Iraq' => ['dial_code' => '+964', 'iso' => 'iq', 'min_digits' => 10, 'max_digits' => 10],
            'Ireland' => ['dial_code' => '+353', 'iso' => 'ie', 'min_digits' => 9, 'max_digits' => 9],
            'Israel' => ['dial_code' => '+972', 'iso' => 'il', 'min_digits' => 9, 'max_digits' => 9],
            'Italy' => ['dial_code' => '+39', 'iso' => 'it', 'min_digits' => 10, 'max_digits' => 10],
            'Jamaica' => ['dial_code' => '+1', 'iso' => 'jm', 'min_digits' => 10, 'max_digits' => 10],
            'Japan' => ['dial_code' => '+81', 'iso' => 'jp', 'min_digits' => 10, 'max_digits' => 10],
            'Jordan' => ['dial_code' => '+962', 'iso' => 'jo', 'min_digits' => 9, 'max_digits' => 9],
            'Kazakhstan' => ['dial_code' => '+7', 'iso' => 'kz', 'min_digits' => 10, 'max_digits' => 10],
            'Kenya' => ['dial_code' => '+254', 'iso' => 'ke', 'min_digits' => 9, 'max_digits' => 9],
            'Kiribati' => ['dial_code' => '+686', 'iso' => 'ki', 'min_digits' => 8, 'max_digits' => 8],
            'Kuwait' => ['dial_code' => '+965', 'iso' => 'kw', 'min_digits' => 8, 'max_digits' => 8],
            'Kyrgyzstan' => ['dial_code' => '+996', 'iso' => 'kg', 'min_digits' => 9, 'max_digits' => 9],
            'Laos' => ['dial_code' => '+856', 'iso' => 'la', 'min_digits' => 9, 'max_digits' => 10],
            'Latvia' => ['dial_code' => '+371', 'iso' => 'lv', 'min_digits' => 8, 'max_digits' => 8],
            'Lebanon' => ['dial_code' => '+961', 'iso' => 'lb', 'min_digits' => 7, 'max_digits' => 8],
            'Lesotho' => ['dial_code' => '+266', 'iso' => 'ls', 'min_digits' => 8, 'max_digits' => 8],
            'Liberia' => ['dial_code' => '+231', 'iso' => 'lr', 'min_digits' => 8, 'max_digits' => 9],
            'Libya' => ['dial_code' => '+218', 'iso' => 'ly', 'min_digits' => 9, 'max_digits' => 9],
            'Liechtenstein' => ['dial_code' => '+423', 'iso' => 'li', 'min_digits' => 7, 'max_digits' => 9],
            'Lithuania' => ['dial_code' => '+370', 'iso' => 'lt', 'min_digits' => 8, 'max_digits' => 8],
            'Luxembourg' => ['dial_code' => '+352', 'iso' => 'lu', 'min_digits' => 9, 'max_digits' => 9],
            'Madagascar' => ['dial_code' => '+261', 'iso' => 'mg', 'min_digits' => 9, 'max_digits' => 9],
            'Malawi' => ['dial_code' => '+265', 'iso' => 'mw', 'min_digits' => 9, 'max_digits' => 9],
            'Malaysia' => ['dial_code' => '+60', 'iso' => 'my', 'min_digits' => 9, 'max_digits' => 10],
            'Maldives' => ['dial_code' => '+960', 'iso' => 'mv', 'min_digits' => 7, 'max_digits' => 7],
            'Mali' => ['dial_code' => '+223', 'iso' => 'ml', 'min_digits' => 8, 'max_digits' => 8],
            'Malta' => ['dial_code' => '+356', 'iso' => 'mt', 'min_digits' => 8, 'max_digits' => 8],
            'Marshall Islands' => ['dial_code' => '+692', 'iso' => 'mh', 'min_digits' => 7, 'max_digits' => 7],
            'Mauritania' => ['dial_code' => '+222', 'iso' => 'mr', 'min_digits' => 8, 'max_digits' => 8],
            'Mauritius' => ['dial_code' => '+230', 'iso' => 'mu', 'min_digits' => 8, 'max_digits' => 8],
            'Mexico' => ['dial_code' => '+52', 'iso' => 'mx', 'min_digits' => 10, 'max_digits' => 10],
            'Micronesia' => ['dial_code' => '+691', 'iso' => 'fm', 'min_digits' => 7, 'max_digits' => 7],
            'Moldova' => ['dial_code' => '+373', 'iso' => 'md', 'min_digits' => 8, 'max_digits' => 8],
            'Monaco' => ['dial_code' => '+377', 'iso' => 'mc', 'min_digits' => 8, 'max_digits' => 9],
            'Mongolia' => ['dial_code' => '+976', 'iso' => 'mn', 'min_digits' => 8, 'max_digits' => 8],
            'Montenegro' => ['dial_code' => '+382', 'iso' => 'me', 'min_digits' => 8, 'max_digits' => 8],
            'Morocco' => ['dial_code' => '+212', 'iso' => 'ma', 'min_digits' => 9, 'max_digits' => 9],
            'Mozambique' => ['dial_code' => '+258', 'iso' => 'mz', 'min_digits' => 9, 'max_digits' => 9],
            'Myanmar' => ['dial_code' => '+95', 'iso' => 'mm', 'min_digits' => 8, 'max_digits' => 10],
            'Namibia' => ['dial_code' => '+264', 'iso' => 'na', 'min_digits' => 9, 'max_digits' => 9],
            'Nauru' => ['dial_code' => '+674', 'iso' => 'nr', 'min_digits' => 7, 'max_digits' => 7],
            'Nepal' => ['dial_code' => '+977', 'iso' => 'np', 'min_digits' => 10, 'max_digits' => 10],
            'Netherlands' => ['dial_code' => '+31', 'iso' => 'nl', 'min_digits' => 9, 'max_digits' => 9],
            'New Zealand' => ['dial_code' => '+64', 'iso' => 'nz', 'min_digits' => 8, 'max_digits' => 10],
            'Nicaragua' => ['dial_code' => '+505', 'iso' => 'ni', 'min_digits' => 8, 'max_digits' => 8],
            'Niger' => ['dial_code' => '+227', 'iso' => 'ne', 'min_digits' => 8, 'max_digits' => 8],
            'Nigeria' => ['dial_code' => '+234', 'iso' => 'ng', 'min_digits' => 10, 'max_digits' => 10],
            'North Korea' => ['dial_code' => '+850', 'iso' => 'kp', 'min_digits' => 8, 'max_digits' => 10],
            'North Macedonia' => ['dial_code' => '+389', 'iso' => 'mk', 'min_digits' => 8, 'max_digits' => 8],
            'Norway' => ['dial_code' => '+47', 'iso' => 'no', 'min_digits' => 8, 'max_digits' => 8],
            'Oman' => ['dial_code' => '+968', 'iso' => 'om', 'min_digits' => 8, 'max_digits' => 8],
            'Pakistan' => ['dial_code' => '+92', 'iso' => 'pk', 'min_digits' => 10, 'max_digits' => 10],
            'Palau' => ['dial_code' => '+680', 'iso' => 'pw', 'min_digits' => 7, 'max_digits' => 7],
            'Panama' => ['dial_code' => '+507', 'iso' => 'pa', 'min_digits' => 7, 'max_digits' => 8],
            'Papua New Guinea' => ['dial_code' => '+675', 'iso' => 'pg', 'min_digits' => 8, 'max_digits' => 8],
            'Paraguay' => ['dial_code' => '+595', 'iso' => 'py', 'min_digits' => 9, 'max_digits' => 9],
            'Peru' => ['dial_code' => '+51', 'iso' => 'pe', 'min_digits' => 9, 'max_digits' => 9],
            'Philippines' => ['dial_code' => '+63', 'iso' => 'ph', 'min_digits' => 10, 'max_digits' => 10],
            'Poland' => ['dial_code' => '+48', 'iso' => 'pl', 'min_digits' => 9, 'max_digits' => 9],
            'Portugal' => ['dial_code' => '+351', 'iso' => 'pt', 'min_digits' => 9, 'max_digits' => 9],
            'Qatar' => ['dial_code' => '+974', 'iso' => 'qa', 'min_digits' => 8, 'max_digits' => 8],
            'Romania' => ['dial_code' => '+40', 'iso' => 'ro', 'min_digits' => 9, 'max_digits' => 10],
            'Russia' => ['dial_code' => '+7', 'iso' => 'ru', 'min_digits' => 10, 'max_digits' => 10],
            'Rwanda' => ['dial_code' => '+250', 'iso' => 'rw', 'min_digits' => 9, 'max_digits' => 9],
            'Saint Kitts and Nevis' => ['dial_code' => '+1', 'iso' => 'kn', 'min_digits' => 10, 'max_digits' => 10],
            'Saint Lucia' => ['dial_code' => '+1', 'iso' => 'lc', 'min_digits' => 10, 'max_digits' => 10],
            'Saint Vincent and the Grenadines' => ['dial_code' => '+1', 'iso' => 'vc', 'min_digits' => 10, 'max_digits' => 10],
            'Samoa' => ['dial_code' => '+685', 'iso' => 'ws', 'min_digits' => 7, 'max_digits' => 7],
            'San Marino' => ['dial_code' => '+378', 'iso' => 'sm', 'min_digits' => 6, 'max_digits' => 10],
            'Sao Tome and Principe' => ['dial_code' => '+239', 'iso' => 'st', 'min_digits' => 7, 'max_digits' => 7],
            'Saudi Arabia' => ['dial_code' => '+966', 'iso' => 'sa', 'min_digits' => 9, 'max_digits' => 9],
            'Senegal' => ['dial_code' => '+221', 'iso' => 'sn', 'min_digits' => 9, 'max_digits' => 9],
            'Serbia' => ['dial_code' => '+381', 'iso' => 'rs', 'min_digits' => 8, 'max_digits' => 9],
            'Seychelles' => ['dial_code' => '+248', 'iso' => 'sc', 'min_digits' => 7, 'max_digits' => 7],
            'Sierra Leone' => ['dial_code' => '+232', 'iso' => 'sl', 'min_digits' => 8, 'max_digits' => 8],
            'Singapore' => ['dial_code' => '+65', 'iso' => 'sg', 'min_digits' => 8, 'max_digits' => 8],
            'Slovakia' => ['dial_code' => '+421', 'iso' => 'sk', 'min_digits' => 9, 'max_digits' => 9],
            'Slovenia' => ['dial_code' => '+386', 'iso' => 'si', 'min_digits' => 8, 'max_digits' => 8],
            'Solomon Islands' => ['dial_code' => '+677', 'iso' => 'sb', 'min_digits' => 7, 'max_digits' => 7],
            'Somalia' => ['dial_code' => '+252', 'iso' => 'so', 'min_digits' => 8, 'max_digits' => 9],
            'South Africa' => ['dial_code' => '+27', 'iso' => 'za', 'min_digits' => 9, 'max_digits' => 9],
            'South Korea' => ['dial_code' => '+82', 'iso' => 'kr', 'min_digits' => 9, 'max_digits' => 10],
            'South Sudan' => ['dial_code' => '+211', 'iso' => 'ss', 'min_digits' => 9, 'max_digits' => 9],
            'Spain' => ['dial_code' => '+34', 'iso' => 'es', 'min_digits' => 9, 'max_digits' => 9],
            'Sri Lanka' => ['dial_code' => '+94', 'iso' => 'lk', 'min_digits' => 9, 'max_digits' => 9],
            'Sudan' => ['dial_code' => '+249', 'iso' => 'sd', 'min_digits' => 9, 'max_digits' => 9],
            'Suriname' => ['dial_code' => '+597', 'iso' => 'sr', 'min_digits' => 7, 'max_digits' => 7],
            'Sweden' => ['dial_code' => '+46', 'iso' => 'se', 'min_digits' => 9, 'max_digits' => 9],
            'Switzerland' => ['dial_code' => '+41', 'iso' => 'ch', 'min_digits' => 9, 'max_digits' => 9],
            'Syria' => ['dial_code' => '+963', 'iso' => 'sy', 'min_digits' => 9, 'max_digits' => 9],
            'Taiwan' => ['dial_code' => '+886', 'iso' => 'tw', 'min_digits' => 9, 'max_digits' => 9],
            'Tajikistan' => ['dial_code' => '+992', 'iso' => 'tj', 'min_digits' => 9, 'max_digits' => 9],
            'Tanzania' => ['dial_code' => '+255', 'iso' => 'tz', 'min_digits' => 9, 'max_digits' => 9],
            'Thailand' => ['dial_code' => '+66', 'iso' => 'th', 'min_digits' => 9, 'max_digits' => 9],
            'Timor-Leste' => ['dial_code' => '+670', 'iso' => 'tl', 'min_digits' => 8, 'max_digits' => 8],
            'Togo' => ['dial_code' => '+228', 'iso' => 'tg', 'min_digits' => 8, 'max_digits' => 8],
            'Tonga' => ['dial_code' => '+676', 'iso' => 'to', 'min_digits' => 7, 'max_digits' => 7],
            'Trinidad and Tobago' => ['dial_code' => '+1', 'iso' => 'tt', 'min_digits' => 10, 'max_digits' => 10],
            'Tunisia' => ['dial_code' => '+216', 'iso' => 'tn', 'min_digits' => 8, 'max_digits' => 8],
            'Turkey' => ['dial_code' => '+90', 'iso' => 'tr', 'min_digits' => 10, 'max_digits' => 10],
            'Turkmenistan' => ['dial_code' => '+993', 'iso' => 'tm', 'min_digits' => 8, 'max_digits' => 8],
            'Tuvalu' => ['dial_code' => '+688', 'iso' => 'tv', 'min_digits' => 7, 'max_digits' => 7],
            'Uganda' => ['dial_code' => '+256', 'iso' => 'ug', 'min_digits' => 9, 'max_digits' => 9],
            'Ukraine' => ['dial_code' => '+380', 'iso' => 'ua', 'min_digits' => 9, 'max_digits' => 9],
            'United Arab Emirates' => ['dial_code' => '+971', 'iso' => 'ae', 'min_digits' => 9, 'max_digits' => 9],
            'United Kingdom' => ['dial_code' => '+44', 'iso' => 'gb', 'min_digits' => 10, 'max_digits' => 11],
            'United States' => ['dial_code' => '+1', 'iso' => 'us', 'min_digits' => 10, 'max_digits' => 10],
            'Uruguay' => ['dial_code' => '+598', 'iso' => 'uy', 'min_digits' => 8, 'max_digits' => 8],
            'Uzbekistan' => ['dial_code' => '+998', 'iso' => 'uz', 'min_digits' => 9, 'max_digits' => 9],
            'Vanuatu' => ['dial_code' => '+678', 'iso' => 'vu', 'min_digits' => 7, 'max_digits' => 7],
            'Vatican City' => ['dial_code' => '+379', 'iso' => 'va', 'min_digits' => 8, 'max_digits' => 8],
            'Venezuela' => ['dial_code' => '+58', 'iso' => 've', 'min_digits' => 10, 'max_digits' => 10],
            'Vietnam' => ['dial_code' => '+84', 'iso' => 'vn', 'min_digits' => 9, 'max_digits' => 10],
            'Yemen' => ['dial_code' => '+967', 'iso' => 'ye', 'min_digits' => 9, 'max_digits' => 9],
            'Zambia' => ['dial_code' => '+260', 'iso' => 'zm', 'min_digits' => 9, 'max_digits' => 9],
            'Zimbabwe' => ['dial_code' => '+263', 'iso' => 'zw', 'min_digits' => 9, 'max_digits' => 9],
        ];
    }
}

